spring:
  application:
    name: seributukang

  datasource:
    url: jdbc:postgresql://localhost:5432/seributukang_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  web:
    resources:
      add-mappings: false

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    id.co.jasapro: DEBUG
    id.co.jasapro.seributukang.modules.provider: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: DEBUG
    org.springframework.beans.factory.support.DefaultListableBeanFactory: DEBUG
    org.springframework.context.support.PostProcessorRegistrationDelegate: DEBUG
    org.hibernate.SQL: DEBUG

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000