spring:
  application:
    name: seributukang

  datasource:
    url: jdbc:postgresql://localhost:5432/seributukang_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  sql:
    init:
      mode: always        # ← run data.sql on every startup
      data-locations: classpath:data.sql

  web:
    resources:
      add-mappings: false

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    id.co.jasapro: DEBUG
    org.hibernate.SQL: DEBUG

app:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000